
const wordsList = [
  // 1–50
  { en: "Abandon", tr: "Terk etmek", options: ["Terk etmek", "Kabul etmek", "Hızlandırmak"] },
  { en: "Acquire", tr: "Edinmek", options: ["Edinmek", "Kaybetmek", "Reddetmek"] },
  { en: "Adequate", tr: "Yeterli", options: ["Yeterli", "Yetersiz", "Zararlı"] },
  { en: "Adjacent", tr: "Bitişik", options: ["Bitişik", "Uzak", "Geçici"] },
  { en: "Advocate", tr: "Savunmak", options: ["Savunmak", "Engellemek", "Gizlemek"] },
  { en: "Allocate", tr: "Tahsis etmek", options: ["Tahsis etmek", "Azaltmak", "Birleştirmek"] },
  { en: "Alter", tr: "Değiştirmek", options: ["Değiştirmek", "Korumak", "Ertelemek"] },
  { en: "Ambiguous", tr: "Belirsiz", options: ["Belirsiz", "Açık", "Kesin"] },
  { en: "Anticipate", tr: "Öngörmek", options: ["Öngörmek", "Unutmak", "Reddetmek"] },
  { en: "Apparent", tr: "Belirgin", options: ["Belirgin", "Gizli", "Nadir"] },
  { en: "Assess", tr: "Değerlendirmek", options: ["Değerlendirmek", "Üretmek", "Dağıtmak"] },
  { en: "Attain", tr: "Ulaşmak", options: ["Ulaşmak", "Kaybetmek", "Vazgeçmek"] },
  { en: "Attribute", tr: "Atfetmek", options: ["Atfetmek", "Ayırmak", "Yasaklamak"] },
  { en: "Aware", tr: "Farkında", options: ["Farkında", "Kararsız", "İlgisiz"] },
  { en: "Beneficial", tr: "Yararlı", options: ["Yararlı", "Zararlı", "Pahalı"] },
  { en: "Cease", tr: "Sona ermek", options: ["Sona ermek", "Başlamak", "Hızlanmak"] },
  { en: "Coherent", tr: "Tutarlı", options: ["Tutarlı", "Çelişkili", "Eksik"] },
  { en: "Coincide", tr: "Çakışmak", options: ["Çakışmak", "Ayrılmak", "Gecikmek"] },
  { en: "Collapse", tr: "Çökmek", options: ["Çökmek", "Gelişmek", "Genişlemek"] },
  { en: "Commence", tr: "Başlamak", options: ["Başlamak", "Bitirmek", "Ertelemek"] },
  { en: "Compensate", tr: "Telafi etmek", options: ["Telafi etmek", "Kısıtlamak", "İhmal etmek"] },
  { en: "Compile", tr: "Derlemek", options: ["Derlemek", "Silmek", "Parçalamak"] },
  { en: "Comprehensive", tr: "Kapsamlı", options: ["Kapsamlı", "Yüzeysel", "Sınırlı"] },
  { en: "Conceive", tr: "Tasarlamak", options: ["Tasarlamak", "Reddetmek", "Unutmak"] },
  { en: "Concentrate", tr: "Odaklanmak", options: ["Odaklanmak", "Dağılmak", "Vazgeçmek"] },
  { en: "Conclude", tr: "Sonuca varmak", options: ["Sonuca varmak", "Başlatmak", "Sorgulamak"] },
  { en: "Conduct", tr: "Yürütmek", options: ["Yürütmek", "Engellemek", "İptal etmek"] },
  { en: "Confer", tr: "Danışmak", options: ["Danışmak", "Geri almak", "Gizlemek"] },
  { en: "Consequence", tr: "Sonuç", options: ["Sonuç", "Neden", "Varsayım"] },
  { en: "Consistent", tr: "Tutarlı", options: ["Tutarlı", "Tutarsız", "Geçici"] },
  { en: "Constitute", tr: "Oluşturmak", options: ["Oluşturmak", "Azaltmak", "Dağıtmak"] },
  { en: "Constrain", tr: "Kısıtlamak", options: ["Kısıtlamak", "Serbest bırakmak", "Desteklemek"] },
  { en: "Contemporary", tr: "Çağdaş", options: ["Çağdaş", "Antik", "Gelecekteki"] },
  { en: "Controversial", tr: "Tartışmalı", options: ["Tartışmalı", "Kesin", "Önemsiz"] },
  { en: "Conventional", tr: "Geleneksel", options: ["Geleneksel", "Yenilikçi", "Olağanüstü"] },
  { en: "Convey", tr: "İletmek", options: ["İletmek", "Gizlemek", "Çarpıtmak"] },
  { en: "Crucial", tr: "Kritik", options: ["Kritik", "Önemsiz", "Geçici"] },
  { en: "Decline", tr: "Azalmak", options: ["Azalmak", "Artmak", "Genişlemek"] },
  { en: "Demonstrate", tr: "Kanıtlamak", options: ["Kanıtlamak", "Gizlemek", "Çürütmek"] },
  { en: "Derive", tr: "Elde etmek", options: ["Elde etmek", "Kaybetmek", "Engellemek"] },
  { en: "Diminish", tr: "Azaltmak", options: ["Azaltmak", "Artırmak", "Korumak"] },
  { en: "Discrepancy", tr: "Uyuşmazlık", options: ["Uyuşmazlık", "Uyum", "Benzerlik"] },
  { en: "Discriminate", tr: "Ayırt etmek", options: ["Ayırt etmek", "Birleştirmek", "Taklit etmek"] },
  { en: "Diverse", tr: "Çeşitli", options: ["Çeşitli", "Tek tip", "Benzer"] },
  { en: "Dominate", tr: "Hâkim olmak", options: ["Hâkim olmak", "Boyun eğmek", "Geri çekilmek"] },
  { en: "Eliminate", tr: "Ortadan kaldırmak", options: ["Ortadan kaldırmak", "Ortaya çıkarmak", "Güçlendirmek"] },
  { en: "Emerge", tr: "Ortaya çıkmak", options: ["Ortaya çıkmak", "Kaybolmak", "Gizlenmek"] },
  { en: "Emphasize", tr: "Vurgulamak", options: ["Vurgulamak", "Gizlemek", "Önemsizleştirmek"] },
  { en: "Enhance", tr: "Geliştirmek", options: ["Geliştirmek", "Zayıflatmak", "Azaltmak"] },
  { en: "Ensure", tr: "Sağlamak", options: ["Sağlamak", "Engellemek", "Risk etmek"] },

  // 51–100
  { en: "Establish", tr: "Kurmak", options: ["Kurmak", "Yıkmak", "Ertelemek"] },
  { en: "Evaluate", tr: "Değerlendirmek", options: ["Değerlendirmek", "Tahmin etmek", "Uygulamak"] },
  { en: "Evident", tr: "Açık", options: ["Açık", "Belirsiz", "İmkânsız"] },
  { en: "Exceed", tr: "Aşmak", options: ["Aşmak", "Altında kalmak", "Azaltmak"] },
  { en: "Exclude", tr: "Dışlamak", options: ["Dışlamak", "Dâhil etmek", "Birleştirmek"] },
  { en: "Exhibit", tr: "Sergilemek", options: ["Sergilemek", "Saklamak", "Yok etmek"] },
  { en: "Expand", tr: "Genişletmek", options: ["Genişletmek", "Daraltmak", "Azaltmak"] },
  { en: "Exploit", tr: "Yararlanmak", options: ["Yararlanmak", "Korumak", "Vazgeçmek"] },
  { en: "Facilitate", tr: "Kolaylaştırmak", options: ["Kolaylaştırmak", "Zorlaştırmak", "Engellemek"] },
  { en: "Fluctuate", tr: "Dalgalanmak", options: ["Dalgalanmak", "Sabit kalmak", "Ortadan kalkmak"] },
  { en: "Furthermore", tr: "Ayrıca", options: ["Ayrıca", "Buna rağmen", "Aksi takdirde"] },
  { en: "Generate", tr: "Üretmek", options: ["Üretmek", "Yok etmek", "Kısıtlamak"] },
  { en: "Hence", tr: "Dolayısıyla", options: ["Dolayısıyla", "Bununla birlikte", "Örneğin"] },
  { en: "Hypothesis", tr: "Hipotez", options: ["Hipotez", "Kanıt", "Sonuç"] },
  { en: "Imply", tr: "İma etmek", options: ["İma etmek", "Reddetmek", "Kanıtlamak"] },
  { en: "Incentive", tr: "Teşvik", options: ["Teşvik", "Engel", "Ceza"] },
  { en: "Inevitable", tr: "Kaçınılmaz", options: ["Kaçınılmaz", "Önlenebilir", "Belirsiz"] },
  { en: "Infer", tr: "Çıkarım yapmak", options: ["Çıkarım yapmak", "Reddetmek", "Ezberlemek"] },
  { en: "Inhibit", tr: "Engellemek", options: ["Engellemek", "Teşvik etmek", "Hızlandırmak"] },
  { en: "Innovative", tr: "Yenilikçi", options: ["Yenilikçi", "Geleneksel", "Etkisiz"] },
  { en: "Integrate", tr: "Bütünleştirmek", options: ["Bütünleştirmek", "Ayırmak", "Sınırlamak"] },
  { en: "Interpret", tr: "Yorumlamak", options: ["Yorumlamak", "Kopyalamak", "Gizlemek"] },
  { en: "Investigate", tr: "Araştırmak", options: ["Araştırmak", "İhmal etmek", "Sonlandırmak"] },
  { en: "Justify", tr: "Gerekçelendirmek", options: ["Gerekçelendirmek", "Çürütmek", "Sorgulamak"] },
  { en: "Maintain", tr: "Sürdürmek", options: ["Sürdürmek", "Terk etmek", "Değiştirmek"] },
  { en: "Manipulate", tr: "Yönlendirmek", options: ["Yönlendirmek", "Tarafsız kalmak", "Serbest bırakmak"] },
  { en: "Marginal", tr: "Sınırlı", options: ["Sınırlı", "Belirleyici", "Kapsamlı"] },
  { en: "Mitigate", tr: "Hafifletmek", options: ["Hafifletmek", "Şiddetlendirmek", "Yaygınlaştırmak"] },
  { en: "Neglect", tr: "İhmal etmek", options: ["İhmal etmek", "Önemsemek", "Geliştirmek"] },
  { en: "Obtain", tr: "Elde etmek", options: ["Elde etmek", "Kaybetmek", "Reddetmek"] },
  { en: "Outcome", tr: "Sonuç", options: ["Sonuç", "Başlangıç", "Yöntem"] },
  { en: "Perceive", tr: "Algılamak", options: ["Algılamak", "Gizlemek", "Unutmak"] },
  { en: "Persistent", tr: "Sürekli", options: ["Sürekli", "Geçici", "Nadir"] },
  { en: "Plausible", tr: "Makul", options: ["Makul", "İmkânsız", "Çelişkili"] },
  { en: "Prevalent", tr: "Yaygın", options: ["Yaygın", "Nadir", "Geçici"] },
  { en: "Prohibit", tr: "Yasaklamak", options: ["Yasaklamak", "İzin vermek", "Teşvik etmek"] },
  { en: "Prominent", tr: "Önde gelen", options: ["Önde gelen", "Önemsiz", "Gizli"] },
  { en: "Reliable", tr: "Güvenilir", options: ["Güvenilir", "Güvenilmez", "Şüpheli"] },
  { en: "Reluctant", tr: "İsteksiz", options: ["İsteksiz", "Hevesli", "Kararlı"] },
  { en: "Resemble", tr: "Benzer olmak", options: ["Benzer olmak", "Farklı olmak", "Karşı çıkmak"] },
  { en: "Restrict", tr: "Kısıtlamak", options: ["Kısıtlamak", "Genişletmek", "Serbest bırakmak"] },
  { en: "Retain", tr: "Korumak", options: ["Korumak", "Elden çıkarmak", "Tüketmek"] },
  { en: "Reveal", tr: "Açığa çıkarmak", options: ["Açığa çıkarmak", "Gizlemek", "Çarpıtmak"] },
  { en: "Significant", tr: "Önemli", options: ["Önemli", "Önemsiz", "Belirsiz"] },
  { en: "Substantial", tr: "Kayda değer", options: ["Kayda değer", "Önemsiz", "Yetersiz"] },
  { en: "Subsequent", tr: "Sonraki", options: ["Sonraki", "Önceki", "Eş zamanlı"] },
  { en: "Sufficient", tr: "Yeterli", options: ["Yeterli", "Yetersiz", "Fazladan"] },
  { en: "Undermine", tr: "Zayıflatmak", options: ["Zayıflatmak", "Güçlendirmek", "Desteklemek"] },
  { en: "Undergo", tr: "Geçirmek", options: ["Geçirmek", "Kaçınmak", "Engellemek"] },
  { en: "Valid", tr: "Geçerli", options: ["Geçerli", "Geçersiz", "Şüpheli"] },
  { en: "Vary", tr: "Değişmek", options: ["Değişmek", "Sabit kalmak", "Azalmak"] },

  // 101–150
  { en: "Abundant", tr: "Bol", options: ["Bol", "Kıt", "Zayıf"] },
  { en: "Accelerate", tr: "Hızlandırmak", options: ["Hızlandırmak", "Yavaşlatmak", "Durdurmak"] },
  { en: "Accompany", tr: "Eşlik etmek", options: ["Eşlik etmek", "Terk etmek", "Engellemek"] },
  { en: "Accumulate", tr: "Biriktirmek", options: ["Biriktirmek", "Dağıtmak", "Tüketmek"] },
  { en: "Accurate", tr: "Doğru", options: ["Doğru", "Yanlış", "Belirsiz"] },
  { en: "Adapt", tr: "Uyum sağlamak", options: ["Uyum sağlamak", "Direnmek", "Reddetmek"] },
  { en: "Adjacent", tr: "Bitişik", options: ["Bitişik", "Uzak", "Bağımsız"] },
  { en: "Adverse", tr: "Olumsuz", options: ["Olumsuz", "Olumlu", "Tarafsız"] },
  { en: "Aggregate", tr: "Toplamak", options: ["Toplamak", "Ayırmak", "Azaltmak"] },
  { en: "Alleviate", tr: "Hafifletmek", options: ["Hafifletmek", "Ağırlaştırmak", "Başlatmak"] },
  { en: "Alter", tr: "Değiştirmek", options: ["Değiştirmek", "Korumak", "Dondurmak"] },
  { en: "Amend", tr: "Düzeltmek", options: ["Düzeltmek", "Bozmak", "Gizlemek"] },
  { en: "Analogous", tr: "Benzer", options: ["Benzer", "Zıt", "Alakasız"] },
  { en: "Annual", tr: "Yıllık", options: ["Yıllık", "Günlük", "Saatlik"] },
  { en: "Anomaly", tr: "Anormallik", options: ["Anormallik", "Düzenlilik", "Benzerlik"] },
  { en: "Apparatus", tr: "Cihaz", options: ["Cihaz", "Kuram", "Yöntem"] },
  { en: "Arbitrary", tr: "Keyfî", options: ["Keyfî", "Zorunlu", "Bilimsel"] },
  { en: "Assemble", tr: "Bir araya getirmek", options: ["Bir araya getirmek", "Dağıtmak", "Yok etmek"] },
  { en: "Attainable", tr: "Ulaşılabilir", options: ["Ulaşılabilir", "İmkânsız", "Belirsiz"] },
  { en: "Bias", tr: "Önyargı", options: ["Önyargı", "Tarafsızlık", "Kanıt"] },
  { en: "Capacity", tr: "Kapasite", options: ["Kapasite", "Eksiklik", "Engel"] },
  { en: "Chronic", tr: "Kronik", options: ["Kronik", "Geçici", "Ani"] },
  { en: "Cite", tr: "Atıfta bulunmak", options: ["Atıfta bulunmak", "İnkâr etmek", "Gizlemek"] },
  { en: "Clarify", tr: "Açıklığa kavuşturmak", options: ["Açıklığa kavuşturmak", "Karıştırmak", "Gizlemek"] },
  { en: "Cluster", tr: "Küme", options: ["Küme", "Boşluk", "Çizgi"] },
  { en: "Complement", tr: "Tamamlamak", options: ["Tamamlamak", "Engellemek", "Eksiltmek"] },
  { en: "Complex", tr: "Karmaşık", options: ["Karmaşık", "Basit", "Açık"] },
  { en: "Component", tr: "Bileşen", options: ["Bileşen", "Bütün", "Sonuç"] },
  { en: "Conceal", tr: "Gizlemek", options: ["Gizlemek", "Açığa çıkarmak", "Göstermek"] },
  { en: "Concurrent", tr: "Eş zamanlı", options: ["Eş zamanlı", "Ardışık", "Gecikmiş"] },
  { en: "Confine", tr: "Sınırlamak", options: ["Sınırlamak", "Genişletmek", "Serbest bırakmak"] },
  { en: "Confirm", tr: "Doğrulamak", options: ["Doğrulamak", "Çürütmek", "Şüphe etmek"] },
  { en: "Conflict", tr: "Çatışma", options: ["Çatışma", "Uyum", "Anlaşma"] },
  { en: "Conform", tr: "Uymak", options: ["Uymak", "Karşı çıkmak", "Ayrılmak"] },
  { en: "Consecutive", tr: "Ardışık", options: ["Ardışık", "Eş zamanlı", "Bağımsız"] },
  { en: "Consensus", tr: "Uzlaşma", options: ["Uzlaşma", "Anlaşmazlık", "Çatışma"] },
  { en: "Conservation", tr: "Koruma", options: ["Koruma", "Tüketim", "Tahribat"] },
  { en: "Considerable", tr: "Kayda değer", options: ["Kayda değer", "Önemsiz", "Yetersiz"] },
  { en: "Consist", tr: "Oluşmak", options: ["Oluşmak", "Dağılmak", "Azalmak"] },
  { en: "Contradict", tr: "Çelişmek", options: ["Çelişmek", "Desteklemek", "Doğrulamak"] },
  { en: "Contrary", tr: "Zıt", options: ["Zıt", "Benzer", "Aynı"] },
  { en: "Contribute", tr: "Katkıda bulunmak", options: ["Katkıda bulunmak", "Engellemek", "Geri çekilmek"] },
  { en: "Convert", tr: "Dönüştürmek", options: ["Dönüştürmek", "Korumak", "Sınırlamak"] },
  { en: "Correspond", tr: "Uyuşmak", options: ["Uyuşmak", "Çelişmek", "Ayrılmak"] },
  { en: "Criteria", tr: "Ölçütler", options: ["Ölçütler", "Sonuçlar", "Varsayımlar"] },
  { en: "Deduce", tr: "Sonuç çıkarmak", options: ["Sonuç çıkarmak", "Varsaymak", "Reddetmek"] },
  { en: "Deficiency", tr: "Eksiklik", options: ["Eksiklik", "Fazlalık", "Yeterlilik"] },
  { en: "Deviate", tr: "Sapmak", options: ["Sapmak", "Uymak", "Sürdürmek"] },
  { en: "Devote", tr: "Adamak", options: ["Adamak", "Vazgeçmek", "Engellemek"] },
  { en: "Disrupt", tr: "Aksatmak", options: ["Aksatmak", "Düzenlemek", "Kolaylaştırmak"] },

  // 151–200
  { en: "Distinct", tr: "Belirgin", options: ["Belirgin", "Belirsiz", "Örtüşen"] },
  { en: "Distort", tr: "Çarpıtmak", options: ["Çarpıtmak", "Doğrulamak", "Açıklamak"] },
  { en: "Distribute", tr: "Dağıtmak", options: ["Dağıtmak", "Toplamak", "Saklamak"] },
  { en: "Dramatic", tr: "Çarpıcı", options: ["Çarpıcı", "Önemsiz", "Yavaş"] },
  { en: "Durable", tr: "Dayanıklı", options: ["Dayanıklı", "Kırılgan", "Geçici"] },
  { en: "Elaborate", tr: "Ayrıntılı", options: ["Ayrıntılı", "Yüzeysel", "Basit"] },
  { en: "Encounter", tr: "Karşılaşmak", options: ["Karşılaşmak", "Kaçınmak", "Terk etmek"] },
  { en: "Equivalent", tr: "Eşdeğer", options: ["Eşdeğer", "Zıt", "Eksik"] },
  { en: "Eradicate", tr: "Yok etmek", options: ["Yok etmek", "Geliştirmek", "Korumak"] },
  { en: "Essential", tr: "Temel", options: ["Temel", "Gereksiz", "İkincil"] },
  { en: "Ethical", tr: "Etik", options: ["Etik", "Yasadışı", "Etkisiz"] },
  { en: "Exaggerate", tr: "Abartmak", options: ["Abartmak", "Küçümsemek", "Doğrulamak"] },
  { en: "Exhaust", tr: "Tüketmek", options: ["Tüketmek", "Yenilemek", "Biriktirmek"] },
  { en: "Explicit", tr: "Açık", options: ["Açık", "Örtük", "Belirsiz"] },
  { en: "Exposure", tr: "Maruz kalma", options: ["Maruz kalma", "Korunma", "Kaçınma"] },
  { en: "External", tr: "Dışsal", options: ["Dışsal", "İçsel", "Merkezî"] },
  { en: "Feasible", tr: "Uygulanabilir", options: ["Uygulanabilir", "İmkânsız", "Zararlı"] },
  { en: "Finite", tr: "Sonlu", options: ["Sonlu", "Sonsuz", "Belirsiz"] },
  { en: "Formulate", tr: "Formüle etmek", options: ["Formüle etmek", "Çürütmek", "Dağıtmak"] },
  { en: "Foster", tr: "Geliştirmek", options: ["Geliştirmek", "Engellemek", "Azaltmak"] },
  { en: "Fundamental", tr: "Temel", options: ["Temel", "Yüzeysel", "İkincil"] },
  { en: "Furthermore", tr: "Ayrıca", options: ["Ayrıca", "Buna rağmen", "Sonuç olarak"] },
  { en: "Implement", tr: "Uygulamak", options: ["Uygulamak", "Ertelemek", "İptal etmek"] },
  { en: "Impose", tr: "Dayatmak", options: ["Dayatmak", "Kaldırmak", "Öneride bulunmak"] },
  { en: "Incorporate", tr: "Dâhil etmek", options: ["Dâhil etmek", "Hariç tutmak", "Ayırmak"] },
  { en: "Induce", tr: "Neden olmak", options: ["Neden olmak", "Önlemek", "Azaltmak"] },
  { en: "Inefficient", tr: "Verimsiz", options: ["Verimsiz", "Verimli", "Etkili"] },
  { en: "Inferior", tr: "Daha düşük", options: ["Daha düşük", "Üstün", "Eşdeğer"] },
  { en: "Infrastructure", tr: "Altyapı", options: ["Altyapı", "Üstyapı", "Çıktı"] },
  { en: "Inherent", tr: "Doğasında bulunan", options: ["Doğasında bulunan", "Sonradan eklenen", "Geçici"] },
  { en: "Initial", tr: "Başlangıçtaki", options: ["Başlangıçtaki", "Sonraki", "Nihai"] },
  { en: "Initiate", tr: "Başlatmak", options: ["Başlatmak", "Bitirmek", "Engellemek"] },
  { en: "Inspect", tr: "İncelemek", options: ["İncelemek", "İhmal etmek", "Gizlemek"] },
  { en: "Intense", tr: "Yoğun", options: ["Yoğun", "Hafif", "Yüzeysel"] },
  { en: "Interfere", tr: "Müdahale etmek", options: ["Müdahale etmek", "Desteklemek", "Geri çekilmek"] },
  { en: "Interval", tr: "Aralık", options: ["Aralık", "Süreklilik", "Başlangıç"] },
  { en: "Intrinsic", tr: "İçsel", options: ["İçsel", "Dışsal", "Yapay"] },
  { en: "Latter", tr: "İkincisi", options: ["İkincisi", "Birincisi", "Her ikisi"] },
  { en: "Legitimate", tr: "Meşru", options: ["Meşru", "Yasadışı", "Şüpheli"] },
  { en: "Magnitude", tr: "Büyüklük", options: ["Büyüklük", "Önemsizlik", "Süre"] },
  { en: "Nevertheless", tr: "Bununla birlikte", options: ["Bununla birlikte", "Bu nedenle", "Örneğin"] },
  { en: "Notion", tr: "Kavram", options: ["Kavram", "Kanıt", "Yöntem"] },
  { en: "Overcome", tr: "Üstesinden gelmek", options: ["Üstesinden gelmek", "Teslim olmak", "Ertelemek"] },
  { en: "Preliminary", tr: "Ön hazırlık niteliğinde", options: ["Ön hazırlık niteliğinde", "Nihai", "Kesinleşmiş"] },
  { en: "Presume", tr: "Varsaymak", options: ["Varsaymak", "Kanıtlamak", "Reddetmek"] },
  { en: "Proportion", tr: "Oran", options: ["Oran", "Fark", "Neden"] },
  { en: "Regulate", tr: "Düzenlemek", options: ["Düzenlemek", "Serbest bırakmak", "Bozmak"] },
  { en: "Reinforce", tr: "Güçlendirmek", options: ["Güçlendirmek", "Zayıflatmak", "Azaltmak"] },
  { en: "Restore", tr: "Eski hâline getirmek", options: ["Eski hâline getirmek", "Yok etmek", "Değiştirmek"] },
  { en: "Restrict", tr: "Sınırlamak", options: ["Sınırlamak", "Genişletmek", "Serbest bırakmak"] }
];

// Dağhan Arya Seviyesi (5. ve 6. Sınıf Düzeyi 100 Kelimelik Kolay Liste)
const daghanAryaWordsList = [
    { en: "Apple", tr: "Elma", options: ["Elma", "Muz", "Çilek"] },
    { en: "Cat", tr: "Kedi", options: ["Kedi", "Köpek", "Kuş"] },
    { en: "Pencil", tr: "Kalem", options: ["Kalem", "Kitap", "Çanta"] },
    { en: "School", tr: "Okul", options: ["Okul", "Ev", "Park"] },
    { en: "Teacher", tr: "Öğretmen", options: ["Öğretmen", "Öğrenci", "Doktor"] },
    { en: "Book", tr: "Kitap", options: ["Kitap", "Defter", "Silgi"] },
    { en: "Friend", tr: "Arkadaş", options: ["Arkadaş", "Düşman", "Yabancı"] },
    { en: "Family", tr: "Aile", options: ["Aile", "Komşu", "Sınıf"] },
    { en: "Water", tr: "Su", options: ["Su", "Süt", "Meyve Suyu"] },
    { en: "Sun", tr: "Güneş", options: ["Güneş", "Ay", "Yıldız"] },
    { en: "Happy", tr: "Mutlu", options: ["Mutlu", "Üzgün", "Kızgın"] },
    { en: "Game", tr: "Oyun", options: ["Oyun", "Ders", "Ödev"] },
    { en: "Breakfast", tr: "Kahvaltı", options: ["Kahvaltı", "Öğle Yemeği", "Akşam Yemeği"] },
    { en: "Classroom", tr: "Sınıf", options: ["Sınıf", "Kütüphane", "Bahçe"] },
    { en: "Library", tr: "Kütüphane", options: ["Kütüphane", "Sınıf", "Mutfak"] },
    { en: "Weather", tr: "Hava Durumu", options: ["Hava Durumu", "Mevsim", "Saat"] },
    { en: "Summer", tr: "Yaz", options: ["Yaz", "Kış", "İlkbahar"] },
    { en: "Winter", tr: "Kış", options: ["Kış", "Yaz", "Sonbahar"] },
    { en: "Animal", tr: "Hayvan", options: ["Hayvan", "Bitki", "İnsan"] },
    { en: "Computer", tr: "Bilgisayar", options: ["Bilgisayar", "Telefon", "Televizyon"] },
    { en: "Dog", tr: "Köpek", options: ["Köpek", "Kedi", "Tavşan"] },
    { en: "Bird", tr: "Kuş", options: ["Kuş", "Balık", "Kelebek"] },
    { en: "Milk", tr: "Süt", options: ["Süt", "Su", "Çay"] },
    { en: "Bread", tr: "Ekmek", options: ["Ekmek", "Peynir", "Zeytin"] },
    { en: "Cheese", tr: "Peynir", options: ["Peynir", "Ekmek", "Yumurta"] },
    { en: "Egg", tr: "Yumurta", options: ["Yumurta", "Et", "Süt"] },
    { en: "House", tr: "Ev", options: ["Ev", "Okul", "Hastane"] },
    { en: "Garden", tr: "Bahçe", options: ["Bahçe", "Oda", "Mutfak"] },
    { en: "Door", tr: "Kapı", options: ["Kapı", "Pencere", "Duvar"] },
    { en: "Window", tr: "Pencere", options: ["Pencere", "Kapı", "Masa"] },
    { en: "Table", tr: "Masa", options: ["Masa", "Sandalye", "Yatak"] },
    { en: "Chair", tr: "Sandalye", options: ["Sandalye", "Masa", "Koltuk"] },
    { en: "Student", tr: "Öğrenci", options: ["Öğrenci", "Öğretmen", "Müdür"] },
    { en: "Notebook", tr: "Defter", options: ["Defter", "Kitap", "Kalem"] },
    { en: "Eraser", tr: "Silgi", options: ["Silgi", "Kalem", "Cetvel"] },
    { en: "Ruler", tr: "Cetvel", options: ["Cetvel", "Silgi", "Makas"] },
    { en: "Scissors", tr: "Makas", options: ["Makas", "Kalem", "Boya"] },
    { en: "Color", tr: "Renk", options: ["Renk", "Şekil", "Sayı"] },
    { en: "Red", tr: "Kırmızı", options: ["Kırmızı", "Mavi", "Yeşil"] },
    { en: "Blue", tr: "Mavi", options: ["Mavi", "Sarı", "Kırmızı"] },
    { en: "Green", tr: "Yeşil", options: ["Yeşil", "Siyah", "Beyaz"] },
    { en: "Yellow", tr: "Sarı", options: ["Sarı", "Turuncu", "Mor"] },
    { en: "Orange", tr: "Turuncu", options: ["Turuncu", "Pembe", "Sarı"] },
    { en: "Pink", tr: "Pembe", options: ["Pembe", "Mor", "Kırmızı"] },
    { en: "Black", tr: "Siyah", options: ["Siyah", "Beyaz", "Gri"] },
    { en: "White", tr: "Beyaz", options: ["Beyaz", "Siyah", "Kahverengi"] },
    { en: "Mother", tr: "Anne", options: ["Anne", "Baba", "Kardeş"] },
    { en: "Father", tr: "Baba", options: ["Baba", "Anne", "Dede"] },
    { en: "Brother", tr: "Erkek Kardeş", options: ["Erkek Kardeş", "Kız Kardeş", "Kuzen"] },
    { en: "Sister", tr: "Kız Kardeş", options: ["Kız Kardeş", "Erkek Kardeş", "Teyze"] },
    { en: "Baby", tr: "Bebek", options: ["Bebek", "Çocuk", "Yetişkin"] },
    { en: "Head", tr: "Baş / Kafa", options: ["Baş / Kafa", "Kol", "Bacak"] },
    { en: "Eye", tr: "Göz", options: ["Göz", "Kulak", "Burun"] },
    { en: "Ear", tr: "Kulak", options: ["Kulak", "Göz", "Ağız"] },
    { en: "Nose", tr: "Burun", options: ["Burun", "Ağız", "Diş"] },
    { en: "Mouth", tr: "Ağız", options: ["Ağız", "Dil", "Göz"] },
    { en: "Hand", tr: "El", options: ["El", "Ayak", "Kol"] },
    { en: "Foot", tr: "Ayak", options: ["Ayak", "Bacak", "Diz"] },
    { en: "Shirt", tr: "Gömlek", options: ["Gömlek", "Pantolon", "Ayakkabı"] },
    { en: "Shoes", tr: "Ayakkabı", options: ["Ayakkabı", "Çorap", "Şapka"] },
    { en: "Hat", tr: "Şapka", options: ["Şapka", "Gözlük", "Kemer"] },
    { en: "Sunny", tr: "Güneşli", options: ["Güneşli", "Yağmurlu", "Karlı"] },
    { en: "Rainy", tr: "Yağmurlu", options: ["Yağmurlu", "Rüzgarlı", "Güneşli"] },
    { en: "Snowy", tr: "Karlı", options: ["Karlı", "Bulutlu", "Sıcak"] },
    { en: "Windy", tr: "Rüzgarlı", options: ["Rüzgarlı", "Sisli", "Soğuk"] },
    { en: "Cold", tr: "Soğuk", options: ["Soğuk", "Sıcak", "Ilık"] },
    { en: "Hot", tr: "Sıcak", options: ["Sıcak", "Soğuk", "Ilık"] },
    { en: "Big", tr: "Büyük", options: ["Büyük", "Küçük", "Uzun"] },
    { en: "Small", tr: "Küçük", options: ["Küçük", "Büyük", "Kısa"] },
    { en: "Tall", tr: "Uzun", options: ["Uzun", "Kısa", "Geniş"] },
    { en: "Short", tr: "Kısa", options: ["Kısa", "Uzun", "Yüksek"] },
    { en: "Fast", tr: "Hızlı", options: ["Hızlı", "Yavaş", "Ağır"] },
    { en: "Slow", tr: "Yavaş", options: ["Yavaş", "Hızlı", "Kolay"] },
    { en: "Sad", tr: "Üzgün", options: ["Üzgün", "Mutlu", "Yorgun"] },
    { en: "Tired", tr: "Yorgun", options: ["Yorgun", "Enerjik", "Hasta"] },
    { en: "Hungry", tr: "Aç", options: ["Aç", "Tok", "Susuz"] },
    { en: "Thirsty", tr: "Susamış", options: ["Susamış", "Aç", "Uykulu"] },
    { en: "Run", tr: "Koşmak", options: ["Koşmak", "Yürümek", "Zıplamak"] },
    { en: "Jump", tr: "Zıplamak", options: ["Zıplamak", "Oturmak", "Uyumak"] },
    { en: "Swim", tr: "Yüzmek", options: ["Yüzmek", "Uçmak", "Kaymak"] },
    { en: "Fly", tr: "Uçmak", options: ["Uçmak", "Yürümek", "Yüzmek"] },
    { en: "Read", tr: "Okumak", options: ["Okumak", "Yazmak", "Çizmek"] },
    { en: "Write", tr: "Yazmak", options: ["Yazmak", "Okumak", "Dinlemek"] },
    { en: "Listen", tr: "Dinlemek", options: ["Dinlemek", "Konuşmak", "İzlemek"] },
    { en: "Speak", tr: "Konuşmak", options: ["Konuşmak", "Susmak", "Dinlemek"] },
    { en: "Eat", tr: "Yemek", options: ["Yemek", "İçmek", "Pişirmek"] },
    { en: "Drink", tr: "İçmek", options: ["İçmek", "Yemek", "Satın Almak"] },
    { en: "Sleep", tr: "Uyumak", options: ["Uyumak", "Uyanmak", "Dinlenmek"] },
    { en: "Wake up", tr: "Uyanmak", options: ["Uyanmak", "Uyumak", "Yatmak"] },
    { en: "Doctor", tr: "Doktor", options: ["Doktor", "Hemşire", "Mühendis"] },
    { en: "Nurse", tr: "Hemşire", options: ["Hemşire", "Doktor", "Polis"] },
    { en: "Police", tr: "Polis", options: ["Polis", "Itfaiyeci", "Asker"] },
    { en: "Driver", tr: "Sürücü", options: ["Sürücü", "Pilot", "Kaptan"] },
    { en: "Music", tr: "Müzik", options: ["Müzik", "Resim", "Spor"] },
    { en: "Art", tr: "Resim / Sanat", options: ["Resim / Sanat", "Müzik", "Tarih"] },
    { en: "Math", tr: "Matematik", options: ["Matematik", "Fen", "Türkçe"] },
    { en: "Science", tr: "Fen Bilgisi", options: ["Fen Bilgisi", "Coğrafya", "Tarih"] },
    { en: "Clock", tr: "Saat", options: ["Saat", "Takvim", "Zaman"] },
    { en: "Money", tr: "Para", options: ["Para", "Banka", "Cüzdan"] },
    { en: "Gift", tr: "Hediye", options: ["Hediye", "Kutu", "Sürpriz"] }
];