
const wordsList = [
  // 1–50
  { en: "Abandon", tr: "Terk etmek", options: ["Terk etmek", "Kabul etmek", "Hızlandırmak"] },
  { en: "Acquire", tr: "Edinmek", options: ["Edinmek", "Kaybetmek", "Reddetmek"] },
  { en: "Adequate", tr: "Yeterli", options: ["Yeterli", "Yetersiz", "Zararlı"] },
  { en: "Adjacent", tr: "Bitişik", options: ["Bitişik", "Uzak", "Geçici"] },
  { en: "Advocate", tr: "Savunmak", options: ["Savunmak", "Engellemek", "Gizlemek"] },
  { en: "Allocate", tr: "Tahsis etmek", options: ["Tahsis etmek", "Azaltmak", "Birleştirmek"] },
  { en: "Alter", tr: "Değiştirmek", options: ["Değiştirmek", "Korumak", "Ertelemek"] },
  { en: "Ambiguous", tr: "Belirsiz", options: ["Belirsiz", "Açık", "Kesin"] },
  { en: "Anticipate", tr: "Öngörmek", options: ["Öngörmek", "Unutmak", "Reddetmek"] },
  { en: "Apparent", tr: "Belirgin", options: ["Belirgin", "Gizli", "Nadir"] },
  { en: "Assess", tr: "Değerlendirmek", options: ["Değerlendirmek", "Üretmek", "Dağıtmak"] },
  { en: "Attain", tr: "Ulaşmak", options: ["Ulaşmak", "Kaybetmek", "Vazgeçmek"] },
  { en: "Attribute", tr: "Atfetmek", options: ["Atfetmek", "Ayırmak", "Yasaklamak"] },
  { en: "Aware", tr: "Farkında", options: ["Farkında", "Kararsız", "İlgisiz"] },
  { en: "Beneficial", tr: "Yararlı", options: ["Yararlı", "Zararlı", "Pahalı"] },
  { en: "Cease", tr: "Sona ermek", options: ["Sona ermek", "Başlamak", "Hızlanmak"] },
  { en: "Coherent", tr: "Tutarlı", options: ["Tutarlı", "Çelişkili", "Eksik"] },
  { en: "Coincide", tr: "Çakışmak", options: ["Çakışmak", "Ayrılmak", "Gecikmek"] },
  { en: "Collapse", tr: "Çökmek", options: ["Çökmek", "Gelişmek", "Genişlemek"] },
  { en: "Commence", tr: "Başlamak", options: ["Başlamak", "Bitirmek", "Ertelemek"] },
  { en: "Compensate", tr: "Telafi etmek", options: ["Telafi etmek", "Kısıtlamak", "İhmal etmek"] },
  { en: "Compile", tr: "Derlemek", options: ["Derlemek", "Silmek", "Parçalamak"] },
  { en: "Comprehensive", tr: "Kapsamlı", options: ["Kapsamlı", "Yüzeysel", "Sınırlı"] },
  { en: "Conceive", tr: "Tasarlamak", options: ["Tasarlamak", "Reddetmek", "Unutmak"] },
  { en: "Concentrate", tr: "Odaklanmak", options: ["Odaklanmak", "Dağılmak", "Vazgeçmek"] },
  { en: "Conclude", tr: "Sonuca varmak", options: ["Sonuca varmak", "Başlatmak", "Sorgulamak"] },
  { en: "Conduct", tr: "Yürütmek", options: ["Yürütmek", "Engellemek", "İptal etmek"] },
  { en: "Confer", tr: "Danışmak", options: ["Danışmak", "Geri almak", "Gizlemek"] },
  { en: "Consequence", tr: "Sonuç", options: ["Sonuç", "Neden", "Varsayım"] },
  { en: "Consistent", tr: "Tutarlı", options: ["Tutarlı", "Tutarsız", "Geçici"] },
  { en: "Constitute", tr: "Oluşturmak", options: ["Oluşturmak", "Azaltmak", "Dağıtmak"] },
  { en: "Constrain", tr: "Kısıtlamak", options: ["Kısıtlamak", "Serbest bırakmak", "Desteklemek"] },
  { en: "Contemporary", tr: "Çağdaş", options: ["Çağdaş", "Antik", "Gelecekteki"] },
  { en: "Controversial", tr: "Tartışmalı", options: ["Tartışmalı", "Kesin", "Önemsiz"] },
  { en: "Conventional", tr: "Geleneksel", options: ["Geleneksel", "Yenilikçi", "Olağanüstü"] },
  { en: "Convey", tr: "İletmek", options: ["İletmek", "Gizlemek", "Çarpıtmak"] },
  { en: "Crucial", tr: "Kritik", options: ["Kritik", "Önemsiz", "Geçici"] },
  { en: "Decline", tr: "Azalmak", options: ["Azalmak", "Artmak", "Genişlemek"] },
  { en: "Demonstrate", tr: "Kanıtlamak", options: ["Kanıtlamak", "Gizlemek", "Çürütmek"] },
  { en: "Derive", tr: "Elde etmek", options: ["Elde etmek", "Kaybetmek", "Engellemek"] },
  { en: "Diminish", tr: "Azaltmak", options: ["Azaltmak", "Artırmak", "Korumak"] },
  { en: "Discrepancy", tr: "Uyuşmazlık", options: ["Uyuşmazlık", "Uyum", "Benzerlik"] },
  { en: "Discriminate", tr: "Ayırt etmek", options: ["Ayırt etmek", "Birleştirmek", "Taklit etmek"] },
  { en: "Diverse", tr: "Çeşitli", options: ["Çeşitli", "Tek tip", "Benzer"] },
  { en: "Dominate", tr: "Hâkim olmak", options: ["Hâkim olmak", "Boyun eğmek", "Geri çekilmek"] },
  { en: "Eliminate", tr: "Ortadan kaldırmak", options: ["Ortadan kaldırmak", "Ortaya çıkarmak", "Güçlendirmek"] },
  { en: "Emerge", tr: "Ortaya çıkmak", options: ["Ortaya çıkmak", "Kaybolmak", "Gizlenmek"] },
  { en: "Emphasize", tr: "Vurgulamak", options: ["Vurgulamak", "Gizlemek", "Önemsizleştirmek"] },
  { en: "Enhance", tr: "Geliştirmek", options: ["Geliştirmek", "Zayıflatmak", "Azaltmak"] },
  { en: "Ensure", tr: "Sağlamak", options: ["Sağlamak", "Engellemek", "Risk etmek"] },

 
];

// Dağhan Arya Seviyesi (5. ve 6. Sınıf Düzeyi 100 Kelimelik Kolay Liste)
const daghanAryaWordsList = [
    { en: "Apple", tr: "Elma", options: ["Elma", "Muz", "Çilek"] },
    { en: "Cat", tr: "Kedi", options: ["Kedi", "Köpek", "Kuş"] },
    { en: "Pencil", tr: "Kalem", options: ["Kalem", "Kitap", "Çanta"] },
    { en: "School", tr: "Okul", options: ["Okul", "Ev", "Park"] },
    { en: "Teacher", tr: "Öğretmen", options: ["Öğretmen", "Öğrenci", "Doktor"] },
    { en: "Book", tr: "Kitap", options: ["Kitap", "Defter", "Silgi"] },
    { en: "Friend", tr: "Arkadaş", options: ["Arkadaş", "Düşman", "Yabancı"] },
    { en: "Family", tr: "Aile", options: ["Aile", "Komşu", "Sınıf"] },
    { en: "Water", tr: "Su", options: ["Su", "Süt", "Meyve Suyu"] },
    { en: "Sun", tr: "Güneş", options: ["Güneş", "Ay", "Yıldız"] },
    { en: "Happy", tr: "Mutlu", options: ["Mutlu", "Üzgün", "Kızgın"] },
    { en: "Game", tr: "Oyun", options: ["Oyun", "Ders", "Ödev"] },
    { en: "Breakfast", tr: "Kahvaltı", options: ["Kahvaltı", "Öğle Yemeği", "Akşam Yemeği"] },
    { en: "Classroom", tr: "Sınıf", options: ["Sınıf", "Kütüphane", "Bahçe"] },
    { en: "Library", tr: "Kütüphane", options: ["Kütüphane", "Sınıf", "Mutfak"] },
    { en: "Weather", tr: "Hava Durumu", options: ["Hava Durumu", "Mevsim", "Saat"] },
    { en: "Summer", tr: "Yaz", options: ["Yaz", "Kış", "İlkbahar"] },
    { en: "Winter", tr: "Kış", options: ["Kış", "Yaz", "Sonbahar"] },
    { en: "Animal", tr: "Hayvan", options: ["Hayvan", "Bitki", "İnsan"] },
    { en: "Computer", tr: "Bilgisayar", options: ["Bilgisayar", "Telefon", "Televizyon"] },
    { en: "Dog", tr: "Köpek", options: ["Köpek", "Kedi", "Tavşan"] },
    { en: "Bird", tr: "Kuş", options: ["Kuş", "Balık", "Kelebek"] },
    { en: "Milk", tr: "Süt", options: ["Süt", "Su", "Çay"] },
    { en: "Bread", tr: "Ekmek", options: ["Ekmek", "Peynir", "Zeytin"] },
    { en: "Cheese", tr: "Peynir", options: ["Peynir", "Ekmek", "Yumurta"] },
    { en: "Egg", tr: "Yumurta", options: ["Yumurta", "Et", "Süt"] },
    { en: "House", tr: "Ev", options: ["Ev", "Okul", "Hastane"] },
    { en: "Garden", tr: "Bahçe", options: ["Bahçe", "Oda", "Mutfak"] },
    { en: "Door", tr: "Kapı", options: ["Kapı", "Pencere", "Duvar"] },
    { en: "Window", tr: "Pencere", options: ["Pencere", "Kapı", "Masa"] },
    { en: "Table", tr: "Masa", options: ["Masa", "Sandalye", "Yatak"] },
    { en: "Chair", tr: "Sandalye", options: ["Sandalye", "Masa", "Koltuk"] },
    { en: "Student", tr: "Öğrenci", options: ["Öğrenci", "Öğretmen", "Müdür"] },
    { en: "Notebook", tr: "Defter", options: ["Defter", "Kitap", "Kalem"] },
    { en: "Eraser", tr: "Silgi", options: ["Silgi", "Kalem", "Cetvel"] },
    { en: "Ruler", tr: "Cetvel", options: ["Cetvel", "Silgi", "Makas"] },
    { en: "Scissors", tr: "Makas", options: ["Makas", "Kalem", "Boya"] },
    { en: "Color", tr: "Renk", options: ["Renk", "Şekil", "Sayı"] },
    { en: "Red", tr: "Kırmızı", options: ["Kırmızı", "Mavi", "Yeşil"] },
    { en: "Blue", tr: "Mavi", options: ["Mavi", "Sarı", "Kırmızı"] },
    { en: "Green", tr: "Yeşil", options: ["Yeşil", "Siyah", "Beyaz"] },
    { en: "Yellow", tr: "Sarı", options: ["Sarı", "Turuncu", "Mor"] },
    { en: "Orange", tr: "Turuncu", options: ["Turuncu", "Pembe", "Sarı"] },
    { en: "Pink", tr: "Pembe", options: ["Pembe", "Mor", "Kırmızı"] },
    { en: "Black", tr: "Siyah", options: ["Siyah", "Beyaz", "Gri"] },
    { en: "White", tr: "Beyaz", options: ["Beyaz", "Siyah", "Kahverengi"] },
    { en: "Mother", tr: "Anne", options: ["Anne", "Baba", "Kardeş"] },
    { en: "Father", tr: "Baba", options: ["Baba", "Anne", "Dede"] },
    { en: "Brother", tr: "Erkek Kardeş", options: ["Erkek Kardeş", "Kız Kardeş", "Kuzen"] },
    { en: "Sister", tr: "Kız Kardeş", options: ["Kız Kardeş", "Erkek Kardeş", "Teyze"] },
    { en: "Baby", tr: "Bebek", options: ["Bebek", "Çocuk", "Yetişkin"] },
    { en: "Head", tr: "Baş / Kafa", options: ["Baş / Kafa", "Kol", "Bacak"] },
    { en: "Eye", tr: "Göz", options: ["Göz", "Kulak", "Burun"] },
    { en: "Ear", tr: "Kulak", options: ["Kulak", "Göz", "Ağız"] },
    { en: "Nose", tr: "Burun", options: ["Burun", "Ağız", "Diş"] },
    { en: "Mouth", tr: "Ağız", options: ["Ağız", "Dil", "Göz"] },
    { en: "Hand", tr: "El", options: ["El", "Ayak", "Kol"] },
    { en: "Foot", tr: "Ayak", options: ["Ayak", "Bacak", "Diz"] },
    { en: "Shirt", tr: "Gömlek", options: ["Gömlek", "Pantolon", "Ayakkabı"] },
    { en: "Shoes", tr: "Ayakkabı", options: ["Ayakkabı", "Çorap", "Şapka"] },
    { en: "Hat", tr: "Şapka", options: ["Şapka", "Gözlük", "Kemer"] },
    { en: "Sunny", tr: "Güneşli", options: ["Güneşli", "Yağmurlu", "Karlı"] },
    { en: "Rainy", tr: "Yağmurlu", options: ["Yağmurlu", "Rüzgarlı", "Güneşli"] },
    { en: "Snowy", tr: "Karlı", options: ["Karlı", "Bulutlu", "Sıcak"] },
    { en: "Windy", tr: "Rüzgarlı", options: ["Rüzgarlı", "Sisli", "Soğuk"] },
    { en: "Cold", tr: "Soğuk", options: ["Soğuk", "Sıcak", "Ilık"] },
    { en: "Hot", tr: "Sıcak", options: ["Sıcak", "Soğuk", "Ilık"] },
    { en: "Big", tr: "Büyük", options: ["Büyük", "Küçük", "Uzun"] },
    { en: "Small", tr: "Küçük", options: ["Küçük", "Büyük", "Kısa"] },
    { en: "Tall", tr: "Uzun", options: ["Uzun", "Kısa", "Geniş"] },
    { en: "Short", tr: "Kısa", options: ["Kısa", "Uzun", "Yüksek"] },
    { en: "Fast", tr: "Hızlı", options: ["Hızlı", "Yavaş", "Ağır"] },
    { en: "Slow", tr: "Yavaş", options: ["Yavaş", "Hızlı", "Kolay"] },
    { en: "Sad", tr: "Üzgün", options: ["Üzgün", "Mutlu", "Yorgun"] },
    { en: "Tired", tr: "Yorgun", options: ["Yorgun", "Enerjik", "Hasta"] },
    { en: "Hungry", tr: "Aç", options: ["Aç", "Tok", "Susuz"] },
    { en: "Thirsty", tr: "Susamış", options: ["Susamış", "Aç", "Uykulu"] },
    { en: "Run", tr: "Koşmak", options: ["Koşmak", "Yürümek", "Zıplamak"] },
    { en: "Jump", tr: "Zıplamak", options: ["Zıplamak", "Oturmak", "Uyumak"] },
    { en: "Swim", tr: "Yüzmek", options: ["Yüzmek", "Uçmak", "Kaymak"] },
    { en: "Fly", tr: "Uçmak", options: ["Uçmak", "Yürümek", "Yüzmek"] },
    { en: "Read", tr: "Okumak", options: ["Okumak", "Yazmak", "Çizmek"] },
    { en: "Write", tr: "Yazmak", options: ["Yazmak", "Okumak", "Dinlemek"] },
    { en: "Listen", tr: "Dinlemek", options: ["Dinlemek", "Konuşmak", "İzlemek"] },
    { en: "Speak", tr: "Konuşmak", options: ["Konuşmak", "Susmak", "Dinlemek"] },
    { en: "Eat", tr: "Yemek", options: ["Yemek", "İçmek", "Pişirmek"] },
    { en: "Drink", tr: "İçmek", options: ["İçmek", "Yemek", "Satın Almak"] },
    { en: "Sleep", tr: "Uyumak", options: ["Uyumak", "Uyanmak", "Dinlenmek"] },
    { en: "Wake up", tr: "Uyanmak", options: ["Uyanmak", "Uyumak", "Yatmak"] },
    { en: "Doctor", tr: "Doktor", options: ["Doktor", "Hemşire", "Mühendis"] },
    { en: "Nurse", tr: "Hemşire", options: ["Hemşire", "Doktor", "Polis"] },
    { en: "Police", tr: "Polis", options: ["Polis", "Itfaiyeci", "Asker"] },
    { en: "Driver", tr: "Sürücü", options: ["Sürücü", "Pilot", "Kaptan"] },
    { en: "Music", tr: "Müzik", options: ["Müzik", "Resim", "Spor"] },
    { en: "Art", tr: "Resim / Sanat", options: ["Resim / Sanat", "Müzik", "Tarih"] },
    { en: "Math", tr: "Matematik", options: ["Matematik", "Fen", "Türkçe"] },
    { en: "Science", tr: "Fen Bilgisi", options: ["Fen Bilgisi", "Coğrafya", "Tarih"] },
    { en: "Clock", tr: "Saat", options: ["Saat", "Takvim", "Zaman"] },
    { en: "Money", tr: "Para", options: ["Para", "Banka", "Cüzdan"] },
    { en: "Gift", tr: "Hediye", options: ["Hediye", "Kutu", "Sürpriz"] }
];